import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import store from '@/redux/store'
import { useSelector } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const root = useSelector( (state) => state.root )

  const userHandler = () => {
    store.dispatch({ type: "SET_USER", payload: "new_user_type" });
  }

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Main Route !</p>
        { JSON.stringify(root) }
        <button onClick={ ()=> userHandler() }>dispatch to store</button>
      </main>
    </>
  )
}
